name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v2
        with:
          issue-type: pull-request
          dispatch-type: workflow
          allow-edits: true
          token: ${{ steps.generate-token.outputs.token }}
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            ref=${{ github.event.client_payload.pull_request.head.ref }}
          commands: |
            release

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}

